const characterNames = [
    "Rick Sanchez (Human)",
    "Morty Smith (Human)",
    "Summer Smith (Human)",
    "Beth Smith (Human)",
    "Jerry Smith (Human)",
    "Abadango Cluster Princess (Alien)",
    "Abradolf Lincler (Human)",
    "Adjudicator Rick (Human)",
    "Agency Director (Human)",
    "Alan Rails (Human)",
    "Albert Einstein (Human)",
    "Alexander (Human)",
    "Alien Googah (Alien)",
    "Alien Morty (Alien)",
    "Alien Rick (Alien)",
    "Amish Cyborg (Alien)",
    "Annie (Human)",
    "Antenna Morty (Human)",
    "Antenna Rick (Human)",
    "Ants in my Eyes Johnson (Human)",
    "Aqua Morty (Humanoid)",
    "Aqua Rick (Humanoid)",
    "Arcade Alien (Alien)",
    "Armagheadon (Alien)",
    "Armothy (unknown)",
    "Arthricia (Alien)",
    "Artist Morty (Human)",
    "Attila Starwar (Human)",
    "Baby Legs (Human)",
    "Baby Poopybutthole (Poopybutthole)",
    "Baby Wizard (Alien)",
    "Bearded Lady (Alien)",
    "Beebo (Alien)",
    "Benjamin (Poopybutthole)",
    "Bepisian (Alien)",
    "Beta-Seven (Alien)",
    "Beth Sanchez (Human)",
    "Beth Smith (Human)",
    "Beth Smith (Human)",
    "Beth's Mytholog (Mytholog)",
    "Reverse Rick Outrage (Human)",
    "Revolio Clockberg Jr. (Alien)",
    "Rick D. Sanchez III (Human)",
    "Rick Guilt Rick (Human)",
    "Rick Prime (Human)",
    "Rick D-99 (Human)",
    "Rick D716 (Human)",
    "Rick D716-B (Human)",
    "Rick D716-C (Human)",
    "Rick Sanchez (Human)",
    "Rick J-22 (Human)",
    "Rick K-22 (Human)",
    "Rick Sanchez (Human)",
    "Ricktiminus Sancheziminius (Human)",
    "Riq IV (Human)",
    "Risotto Groupon (Alien)",
    "Risotto's Tentacled Henchman (Alien)",
    "Robot Morty (Robot)",
    "Robot Rick (Robot)",
    "Roger (Human)",
    "Ron Benson (Humanoid)",
    "Ruben (Human)",
    "Samantha (Human)",
    "Scary Brandon (Humanoid)",
    "Scary Glenn (Humanoid)",
    "Scary Terry (Humanoid)",
    "Scroopy Noopers (Alien)",
    "Scropon (Alien)",
    "Scrotian (Animal)",
    "Self-Congratulatory Jerry (Mytholog)",
    "Shimshamian (Alien)",
    "Shlaammi (Alien)",
    "Shleemypants (unknown)",
    "Shmlamantha Shmlicelli (Human)",
    "Shmlangela Shmlobinson-Shmlower (Human)",
    "Shmlona Shmlobinson (Human)",
    "Shmlonathan Shmlower (Human)",
    "Shmlony Shmlicelli (Human)",
    "Shmooglite Runner (Alien)",
    "Shnoopy Bloopers (Alien)",
    "Shrimply Pibbles (Alien)",
    "Simple Rick (Human)",
    "Slaveowner (Human)",
    "Sleepy Gary (Alien)",
    "Slick Morty (Human)",
    "Slippery Stair (Animal)",
    "Slow Mobius (Humanoid)",
    "Slow Rick (Human)",
    "Snuffles (Snowball) (Animal)",
    "Solicitor Rick (Human)",
    "Squanchy (Alien)",
    "Stacy (Human)",
    "Stair Goblin (Alien)",
    "Stealy (Poopybutthole)",
    "Steve (Human)",
    "Steven Phillips (Alien)",
    "Stu (Alien)",
    "Summer Smith (Human)",
    "Summer Smith (Human)",
    "Supernova (Human)",
    "Taddy Mason (Human)",
    "Taint Washer (Human)",
    "Tammy Guetermann (Cronenberg)",
    "Tammy Guetermann (Human)",
    "Teacher Rick (Human)",
    "Terry (Human)",
    "The President (Human)",
    "The President of the Miniverse (Humanoid)",
    "The Scientist Formerly Known as Rick (Human)",
    "Thomas Lipkip (Human)",
    "Three Unknown Things (Alien)",
    "Tinkles (Alien)",
    "Tiny Rick (Human)",
    "Toby Matthews (Human)",
    "Todd Crystal (Alien)",
    "Tom Randolph (Human)",
    "Tommy's Clone (Human)",
    "Tophat Jones (Humanoid)",
    "Tortured Morty (Human)",
    "Toxic Morty (Humanoid)",
    "Toxic Rick (Humanoid)",
    "Traflorkian (Alien)",
    "Trandor (Alien)",
    "Tree Person (Humanoid)",
    "Tricia Lange (Human)",
    "Trunk Morty (Humanoid)",
    "Trunk Man (Humanoid)",
    "Truth Tortoise (Animal)",
    "Tusked Assassin (Alien)",
    "Two Guys with Handlebar Mustaches (Human)",
    "Tumblorkian (Alien)",
    "Unity (Alien)",
    "Unmuscular Michael (Human)",
    "Vampire Master (Vampire)",
    "Vance Maximus (Human)",
    "Veronica Ann Bennet (Alien)",
    "Voltematron (Alien)",
    "Wall Crawling Rick (Humanoid)",
    "Wedding Bartender (Alien)",
    "Weird Rick (Human)",
    "Woman Rick (Alien)",
    "Worldender (Alien)",
    "Yaarb (Alien)",
    "Yellow Headed Doctor (Alien)",
    "Yellow Shirt Rick (Human)",
    "Zarbadar Gloonch (Alien)",
    "Zarbadar's Mytholog (Mytholog)",
    "Zeep Xanflorp (Humanoid)",
    "Zeta Alpha Rick (Human)",
    "Zick Zack (Alien)",
    "Uncle Steve (Alien)",
    "Bearded Morty (Human)",
    "Roy (Human)",
    "Davin (Cronenberg)",
    "Greebybobe (Alien)",
    "Scary Teacher (Humanoid)",
    "Fido (Animal)",
    "Accountant dog (Animal)",
    "Tiny-persons advocacy group lawyer (Humanoid)",
    "Giant Judge (Humanoid)",
    "Morty Jr's interviewer (Human)",
    "Guy from The Bachelor (Human)",
    "Corn detective (Humanoid)",
    "Michael Jackson (Humanoid)",
    "Trunkphobic suspenders guy (Human)",
    "Spiderweb teddy bear (Animal)",
    "Regular Tyrion Lannister (Human)",
    "Quick Mistery Presenter (Human)",
    "Mr. Sneezy (Human)",
    "Two Brothers (Human)",
    "Alien Mexican Armada (Alien)",
    "Giant Cat Monster (Animal)",
    "Old Women (Human)",
    "Trunkphobic guy (Human)",
    "Pro trunk people marriage guy (Human)",
    "Muscular Mannie (Human)",
    "Baby Legs Chief (Human)",
    "Mrs. Sullivan's Boyfriend (Human)",
    "Plutonian Hostess (Alien)",
    "Plutonian Host (Alien)",
    "Rich Plutonian (Alien)",
    "Rich Plutonian (Alien)",
    "Synthetic Laser Eels (Animal)",
    "Pizza-person (Humanoid)",
    "Pizza-person (Humanoid)",
    "Greasy Grandma (Human)",
    "Phone-person (Humanoid)",
    "Phone-person (Humanoid)",
    "Chair-person (Humanoid)",
    "Chair-person (Humanoid)",
    "Chair-homeless (Humanoid)",
    "Chair-waiter (Humanoid)",
    "Doopidoo (Animal)",
    "Super Weird Rick (Human)",
    "Pripudlian (Alien)",
    "Giant Testicle Monster (Animal)",
    "Michael (Human)",
    "Michael's Lawyer (Human)",
    "Veterinary (Human)",
    "Veterinary Nurse (Human)",
    "Bearded Jerry (Human)",
    "Shaved Head Jerry (Human)",
    "Tank Top Jerry (Human)",
    "Pink Polo Shirt Jerry (Human)",
    "Jerryboree Keeper (Alien)",
    "Jerryboree Receptionist (Alien)",
    "Anchor Gear (Alien)",
    "Gear Cop (Alien)",
    "Roy's Mum (Human)",
    "Roy's Wife (Human)",
    "Roy's Son (Human)",
    "Simon (Human)",
    "Vampire Master's Assistant (Vampire)",
    "Arbolian Mentirososian (Alien)",
    "St. Gloopy Noops Nurse (Alien)",
    "Nano Doctor (Alien)",
    "Funny Songs Presenter (Human)",
    "Tax Attorney (Human)",
    "Butthole Ice Cream Guy (Alien)",
    "Traflorkian Journalist (Alien)",
    "Communication's Responsible Rick (Human)",
    "Teleportation's Responsible Rick (Human)",
    "SEAL Team Rick (Human)",
    "SEAL Team Rick (Human)",
    "SEAL Team Rick (Human)",
    "SEAL Team Rick (Human)",
    "Morphizer-XE Customer Support (Alien)",
    "Morphizer-XE Customer Support (Alien)",
    "Morphizer-XE Customer Support (Alien)",
    "Alien Spa Employee (Alien)",
    "Little Voltron (Robot)",
    "Baby Rick (Human)",
    "Bartender Morty (Human)",
    "Dancer Cowboy Morty (Human)",
    "Dancer Morty (Human)",
    "Flower Morty (Human)",
    "Hairdresser Rick (Human)",
    "Journalist Rick (Human)",
    "Private Sector Rick (Human)",
    "Purple Morty (Alien)",
    "Retired General Rick (Human)",
    "Secret Service Rick (Human)",
    "Steve Jobs Rick (Human)",
    "Sheik Rick (Human)",
    "Modern Rick (Human)",
    "Tan Rick (Human)",
    "Visor Rick (Human)",
    "Colonial Rick (Human)",
    "P-Coat Rick (Human)",
    "Chang (Human)",
    "Dr. Eleanor Arroway (Human)",
    "Varrix (Alien)",
    "Secretary of the Interior (Human)",
    "Big Boobed Waitress (Humanoid)",
    "Big Head Morty (Human)",
    "Big Morty (Human)",
    "Body Guard Morty (Human)",
    "Bill (Human)",
    "Bill (Animal)",
    "Birdperson (Alien)",
    "Black Rick (Human)",
    "Blamph (Alien)",
    "Blim Blam (Alien)",
    "Blue Diplomat (Alien)",
    "Blue Footprint Guy (Human)",
    "Blue Shirt Morty (Human)",
    "Bobby Moynihan (Human)",
    "Boobloosian (Alien)",
    "Bootleg Portal Chemist Rick (Human)",
    "Borpocian (Alien)",
    "Brad (Human)",
    "Brad Anderson (Human)",
    "Calypso (Human)",
    "Campaign Manager Morty (Human)",
    "Canklanker Thom (Alien)",
    "Centaur (Humanoid)",
    "Chris (Alien)",
    "Chris (Humanoid)",
    "Coach Feratu (Balik Alistane) (Vampire)",
    "Collector (Alien)",
    "Colossus (Human)",
    "Commander Rick (Human)",
    "Concerto (Humanoid)",
    "Conroy (Robot)",
    "Cool Rick (Human)",
    "Cop Morty (Human)",
    "Cop Rick (Human)",
    "Courier Flap (Alien)",
    "Cousin Nicky (Alien)",
    "Cowboy Morty (Human)",
    "Cowboy Rick (Human)",
    "Crab Spider (Alien)",
    "Creepy Little Girl (Human)",
    "Crocubot (Humanoid)",
    "Cronenberg Rick (Cronenberg)",
    "Cronenberg Morty (Cronenberg)",
    "Cult Leader Morty (Human)",
    "Cyclops Morty (Humanoid)",
    "Cyclops Rick (Humanoid)",
    "Cynthia (Alien)",
    "Cynthia (Human)",
    "Dale (Humanoid)",
    "Daron Jefferson (Alien)",
    "David Letterman (Human)",
    "Davin (Human)",
    "Diablo Verde (Humanoid)",
    "Diane Sanchez (Human)",
    "Dipper and Mabel Mortys (Human)",
    "Tuberculosis (Disease)",
    "Gonorrhea (Disease)",
    "Hepatitis A (Disease)",
    "Hepatitis C (Disease)",
    "Bubonic Plague (Disease)",
    "E. Coli (Disease)",
    "Donna Gueterman (Robot)",
    "Doofus Rick (Human)",
    "Doom-Nomitron (Alien)",
    "Dr. Glip-Glop (Alien)",
    "Dr. Schmidt (Human)",
    "Dr. Wong (Human)",
    "Dr. Xenon Bloom (Humanoid)",
    "Duck With Muscles (Parasite)",
    "Eli (Human)",
    "Eli's Girlfriend (Human)",
    "Eric McMan (Human)",
    "Eric Stoltz Mask Morty (Human)",
    "Ethan (Human)",
    "Ethan (Human)",
    "Evil Beth Clone (Human)",
    "Evil Jerry Clone (Human)",
    "Evil Morty (Human)",
    "Evil Rick (Humanoid)",
    "Evil Summer Clone (Human)",
    "Eyehole Man (Alien)",
    "Fart (Alien)",
    "Fat Morty (Human)",
    "Father Bob (Human)",
    "Flansian (Alien)",
    "Fleeb (Alien)",
    "Frank Palicky (Human)",
    "Frankenstein's Monster (Alien)",
    "Fulgora (Human)",
    "Galactic Federation President (Alien)",
    "Gar Gloonch (Alien)",
    "Gar's Mytholog (Mytholog)",
    "Garblovian (Alien)",
    "Garmanarnar (Alien)",
    "Garment District Rick (Human)",
    "Gazorpazorpfield (Alien)",
    "Gene (Human)",
    "General Nathan (Human)",
    "General Store Owner (Alien)",
    "Genital Washer (Human)",
    "Ghost in a Jar (Alien)",
    "Gibble Snake (Alien)",
    "Glasses Morty (Human)",
    "Glenn (Alien)",
    "Glenn (Human)",
    "Glexo Slim Slom (Alien)",
    "Gobo (Alien)",
    "Goddess Beth (Mytholog)",
    "Gordon Lunas (Human)",
    "Cornvelious Daniel (Alien)",
    "Gwendolyn (Robot)",
    "Hammerhead Morty (Humanoid)",
    "Hamster In Butt (Animal)",
    "Hamurai (Alien)",
    "Harold (Cronenberg)",
    "Hemorrhage (Human)",
    "Hole in the Wall Where the Men Can See it All (unknown)",
    "Hookah Alien (Alien)",
    "Hunter (Human)",
    "Hunter's Father (Human)",
    "Hydrogen-F (Alien)",
    "Ice-T (Alien)",
    "Ideal Jerry (Mytholog)",
    "Insurance Rick (Human)",
    "Investigator Rick (Human)",
    "Invisi-trooper (Human)",
    "Izzy (Animal)",
    "Jackie (Alien)",
    "Jacob (Human)",
    "Jacqueline (Human)",
    "Jaguar (Human)",
    "Jamey (Human)",
    "Jan-Michael Vincent (Human)",
    "Jerry 5-126 (Human)",
    "Jerry Smith (Human)",
    "Celebrity Jerry (Human)",
    "Jerry Smith (Human)",
    "Jerry's Mytholog (Mytholog)",
    "Jessica (Cronenberg)",
    "Jessica (Human)",
    "Jessica's Friend (Human)",
    "Jim (Human)",
    "Johnny Depp (Human)",
    "Jon (Alien)",
    "Joseph Eli Lipkip (Human)",
    "Joyce Smith (Human)",
    "Juggling Rick (Human)",
    "Karen Entity (Alien)",
    "Katarina (Human)",
    "Keara (Alien)",
    "Kevin (Alien)",
    "King Flippy Nips (Alien)",
    "King Jellybean (Alien)",
    "Kozbian (Alien)",
    "Kristen Stewart (Human)",
    "Krombopulos Michael (Alien)",
    "Kyle (Humanoid)",
    "Lady Katana (Humanoid)",
    "Larva Alien (Alien)",
    "Lawyer Morty (Human)",
    "Leonard Smith (Human)",
    "Lighthouse Keeper (Alien)",
    "Lil B (Alien)",
    "Lisa (Alien)",
    "Little Dipper (Humanoid)",
    "Lizard Morty (Humanoid)",
    "Loggins (Alien)",
    "Logic (Human)",
    "Long Sleeved Morty (Human)",
    "Lucy (Human)",
    "Ma-Sha (Alien)",
    "Magma-Q (Alien)",
    "Magnesium-J (Alien)",
    "Man Painted Silver Who Makes Robot Noises (Human)",
    "Maximums Rickimus (Human)",
    "MC Haps (Human)",
    "Mechanical Morty (Robot)",
    "Mechanical Rick (Robot)",
    "Mechanical Summer (Robot)",
    "Mega Fruit Farmer Rick (Human)",
    "Melissa (Humanoid)",
    "Michael Denny and the Denny Singers (Human)",
    "Michael Jenkins (Human)",
    "Michael McLick (Human)",
    "Michael Thompson (Humanoid)",
    "Million Ants (Animal)",
    "Mitch (Human)",
    "Mohawk Guy (Human)",
    "Morty Mart Manager Morty (Human)",
    "Morty Jr. (Humanoid)",
    "Morty Rick (Human)",
    "Morty Smith (Human)",
    "Morty K-22 (Human)",
    "Morty Smith (Human)",
    "Mortytown Loco (Human)",
    "Mr. Beauregard (Alien)",
    "Mr. Benson (Human)",
    "Mr. Booby Buyer (Animal)",
    "Mr. Goldenfold (Cronenberg)",
    "Mr. Goldenfold (Human)",
    "Mr. Marklovitz (Human)",
    "Mr. Meeseeks (Humanoid)",
    "Mr. Needful (Humanoid)",
    "Mr. Poopybutthole (Poopybutthole)",
    "Mrs. Lipkip (Human)",
    "Mrs. Pancakes (Human)",
    "Mrs. Poopybutthole (Poopybutthole)",
    "Mrs. Refrigerator (Alien)",
    "Mrs. Sanchez (Human)",
    "Mrs. Sullivan (Human)",
    "Nancy (Human)",
    "Noob-Noob (Poopybutthole)",
    "Numbericon (Alien)",
    "Octopus Man (Humanoid)",
    "Orthodox Jew (Human)",
    "Pat Gueterman (Robot)",
    "Paul Fleishman (Human)",
    "Pawnshop Clerk (Alien)",
    "Pencilvester (Alien)",
    "Phillip Jacobs (Human)",
    "Photography Cyborg (Robot)",
    "Photography Raptor (Alien)",
    "Pibbles Bodyguard (Alien)",
    "Pichael Thompson (Humanoid)",
    "Pickle Rick (unknown)",
    "Piece of Toast (unknown)",
    "Plumber Rick (Human)",
    "Poncho (Human)",
    "Presidentress of The Mega Gargantuans (Humanoid)",
    "Prince Nebulon (Alien)",
    "Principal Vagina (Cronenberg)",
    "Principal Vagina (Human)",
    "Purge Planet Ruler (Alien)",
    "Quantum Rick (Human)",
    "Randy Dicknose (Human)",
    "Rat Boss (Animal)",
    "Real Fake Doors Salesman (Human)",
    "Regional Manager Rick (Human)",
    "Regular Legs (Human)",
    "Reverse Giraffe (Alien)"
  ];

  export { characterNames };